/* 회원관리*/
use sageori_db;

DROP TABLE IF EXISTS TB_MEMBERS;
CREATE TABLE TB_MEMBERS (
    MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    HP VARCHAR(13) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    DELETED CHAR(1) NOT NULL DEFAULT 'N'
) DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;
